name: Run tests for Task service
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    # Checkout Code
      - name: Get Code
        uses: actions/checkout@v5
    # Setup .Net SDK 9
      - name: Setup .Net SDK 9
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'
    # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore SmartTask360.slnx